title: Niharika Ikkurthy
description: Cardiovascular Disease | Public Health | Chronic Disease Epidemiology

remote_theme: remote_theme: mmistakes/minimal-mistakes@4.24.0
plugins:
  - jekyll-remote-theme
